food/urls.py
from django.urls import path 
from food.views import * 
app_name='nonveg' 


urlpatterns=[
    path('nonveg/',nonveg,name='nonveg'),
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
import food,shopping

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('food/',include('food.urls')), 
    path('shopping/',include('shopping.urls')),
]

shopping/urls.py
from django.urls import path 
from shopping.views import* 
app_name='shirt' 

urlpatterns=[
    path=('shirt/',shirt,name='shirt'),
]

food/models.py
from django.db import models

# Create your models here.

shopping/models.py
from django.db import models

# Create your models here.

food/views.py
from django.shortcuts import render

# Create your views here.


def nonveg(request):
    return render(request,'nonveg.html')

shopping/views.py
from django.shortcuts import render

# Create your views here. 

def shirt(request):
    return render(request,'shirt.html')

templates/nonveg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body> 
    <center>
        <h1>This is represent the nonveg food</h1> 
        <a href="{% url 'shirt:shirt' %}">This page belongs to shopping</a>
    </center>
    
</body>
</html>

templates/shirt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body> 
    <center>
        <h1>This is represent the shopping</h1>  
        <a href="{% url 'nonveg:nonveg' %}"></a>

    </center>
    
</body>
</html>